name-template: 'v$RESOLVED_VERSION'
tag-template: 'v$RESOLVED_VERSION'
categories:
  - title: 🛠 Breaking Changes
    labels:
      - 'breaking change'
  - title: 🚀 Features
    labels:
      - feature
      - enhancement
  - title: 🐛 Bug Fixes
    labels:
      - bugfix
      - fix
  - title: 🚩 Other Changes
    labels:
      - chore
category-template: '#### $TITLE'
change-template: '- $TITLE @$AUTHOR (#$NUMBER)'
change-title-escapes: '\<*_&' # You can add # and @ to disable mentions, and add ` to disable code blocks.
version-resolver:
  major:
    labels:
      - 'major'
  minor:
    labels:
      - 'minor'
  patch:
    labels:
      - 'patch'
  default: patch
template: |
  ### What's Changed

  $CHANGES

autolabeler:
  - label: 'bugfix'
    branch:
      - '/fix\/.+/'
    title:
      - '/fix/i'
  - label: 'feature'
    branch:
      - '/(feat|feature)\/.+/'
    title:
      - '/feat/i'
  - label: 'chore'
    title:
      - '/(chore|docs)/i'
