blank_issues_enabled: false
contact_links:
  - name: Question
    url: https://github.com/grapp-dev/stacks/discussions/categories/q-a
    about: Please ask and answer questions here.
  - name: Feature Request
    url: https://github.com/grapp-dev/stacks/discussions/categories/ideas
    about: Please submit feature requests, feedback and ideas here.
